### ISSUE TITLE
Testen voor een betere performance 

### ISSUE THREAD

**Issue by jtoufik** [Stefan-Espant/performance-matters-oba#7]
Het is van belang in deze leertaak dat wij de performance van onze gemaakte website verbeteren door goed te testen met de aangeboden faseringen.

**Comment by Stefan-Espant** [comment]
Ik heb de website getest en geanalyseerd door middel van Google Lighthouse. Het resultaat en de potentiele oplossingen zijn terug te vinden in de wiki.
